-- DDL -> MANIPULA TABELAS

CREATE TABLE IF NOT EXISTS PROFESSOR ( -- IF NOT EXISTS VALIDA SE UMA TABELA EXISTE OU NÃO E SE EXISTIR PULA O COMANDO
	id SERIAL PRIMARY KEY, -- CHAVE PRIMÁRIO
	nome VARCHAR(50) NOT NULL, -- VARIAVEL OBRIGATÓRIA
	idade INTEGER
	
);

CREATE TABLE IF NOT EXISTS ALUNO(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ANO_ESCOLAR SMALLINT
);

CREATE TABLE IF NOT EXISTS DIRETOR( -- HERANÇA DE PROFESSOR, TEM OS MESMOS CAMPOS E ADCIONA OS PRÓPRIOS
	BONUS DECIMAL(5,2) -- 999,99
) INHERITS (PROFESSOR);


CREATE TABLE NOTA(
	PROFESSOR_ID INTEGER REFERENCES PROFESSOR(ID),
	ALUNO_ID INTEGER REFERENCES ALUNO(ID),
	NOTA DECIMAL(3,1),
	UNIQUE(PROFESSOR_ID, ALUNO_ID) -- O POSTGRES PRECISA DO UNIQUE, POIS NÃO ACEITA MAIS DE UM CAMPO COM A PALAVRA CHAVE "PRIMARY KEY"
);


DROP TABLE NOTA;
CREATE TABLE NOTA(
	PROFESSOR_ID INTEGER,
	ALUNO_ID INTEGER,
	NOTA DECIMAL(3,1),
	UNIQUE(PROFESSOR_ID, ALUNO_ID) -- O POSTGRES PRECISA DO UNIQUE, POIS NÃO ACEITA MAIS DE UM CAMPO COM A PALAVRA CHAVE "PRIMARY KEY"
);

ALTER TABLE NOTA 
ADD CONSTRAINT NOTA_PROFESSO_ID_ID_FKEY -- NOME DA RESTRIÇÃO É DE ESCOLHA DO USUÁRIO, DEVE SER ÚNICO
FOREIGN KEY (PROFESSOR_ID) -- JÁ EXISTIA
REFERENCES PROFESSOR(ID);


ALTER TABLE NOTA 
ADD CONSTRAINT NOTA_NOTA 
CHECK (NOTA < 10.1) -- RESTRIÇAO DE VALORES, ELE VALIDA SE UM VALOR ATENDE A DETERMINADOS PARAMETROS
	-- NOTA DEVE SER MENOR QUE 10.1
;

ALTER TABLE PROFESSOR 
ADD CONSTRAINT PROFESSOR_NOME 
CHECK (LENGTH(NOME) > 3) -- RESTRIÇAO DE VALORES, ELE VALIDA SE UM VALOR ATENDE A DETERMINADOS PARAMETROS
	-- NOME DEVE SER MAIOR QUE 3 CARACTERES
;



-- DELETAM AS TABELAS INTEIRAS
DROP TABLE DIRETOR;
DROP TABLE PROFESSOR; -- SÓ POSSO DELETAR PROFESSO APÓS DELETAR DIRETOR, POR CAUSA DA HERANÇA
DROP TABLE ALUNO CASCADE; -- CASCADE DELETA EM CASCATA -> AFETA OS REGISTROS DE NOTAS

ALTER TABLE IF EXISTS PROFESSOR ADD NUMERO_ARMARIO VARCHAR(20) UNIQUE NOT NULL; -- ADICIONA UMA NOVA COLUNA
ALTER TABLE PROFESSOR DROP COLUMN NUMERO_ARMARIO;  -- DELETA UMA COLUNA
ALTER TABLE PROFESSOR ALTER COLUMN NUMERO_ARMARIO TYPE VARCHAR (30); -- MUDA TIPO COLUNA
ALTER TABLE PROFESSOR RENAME COLUMN NUMERO_ARMARIO TO NOME_ARMARIO; -- MUDA NOME COLUNA


